### ISSUE TITLE
access an entry from a different group

### ISSUE THREAD

**Issue by ishehadeh** [renatoathaydes/go-hash#1]
would It be possible (or make sense) to have the cp command have an extra parameter for the group? So I could log in and type something like `cp -p google google-entry` instead of `group google <entry> cp -p google-entry`

**Comment by renatoathaydes** [comment]
I was thinking of adding that, tbh, but more like `cp -g group -p entry`... currently, you can name groups and entries anything you want... so parsing `google google-entry` is impossible...

**Comment by renatoathaydes** [comment]
BTW hope you notice you can auto-complete with Tab... so typing 2 commands shouldn't be too much of a problem, I think... but anyway, I like the idea of adding this...

**Comment by renatoathaydes** [comment]
Implemented feature in version 0.8.0.

See the README and `help entry` for details.
