### ISSUE TITLE
Windows: cmd.exe visual preferences altered

### ISSUE THREAD

**Issue by bourbonspecial** [renatoathaydes/go-hash#3]
On running go-hash the background colour and text colour set in cmd.exe are reset to default (black background, white text) rather than preserving the user preference.

**Comment by renatoathaydes** [comment]
I haven't tested in Windows yet, sorry for that!! I will try to test it as soon as possible and make a new release. Thanks for letting me know.

**Comment by renatoathaydes** [comment]
I've checked Mac and Linux and it works correctly on both: the prompt is shown in red, without altering any other colors.
I think the terminal you used does not support ANSI colors. Can you try some terminal like Cygwin, PowerShell or GitShell (that comes with [GitHub Desktop](https://desktop.github.com/))?

**Comment by bourbonspecial** [comment]
Tried in powershell and git bash (I think this is what you meant by git shell? I downloaded github desktop to double check but didn't see anything called git shell that was installed), no joy in either. Looks like git bash is built on top of cmd.exe which is probably why it's not working there.

**Comment by renatoathaydes** [comment]
Looks like Windows 10 disabled ANSI by default.

See https://github.com/symfony/symfony/issues/19520 and https://github.com/composer/composer/issues/5542

In summary, can you try starting `go-hash` with the `--no-ansi` flag?

I will try to fix anyway like the other projects did!

**Comment by renatoathaydes** [comment]
Ah, and sorry, I mean Git bash, not shell.

**Comment by renatoathaydes** [comment]
Hi again... I only have Windows 7 on a really old machine to test this... and here's what I got:

![gohash-windows](https://user-images.githubusercontent.com/1901277/34533278-d9418738-f0b9-11e7-8d91-804905d43fcd.png)

It seems to work fine (but it does crash when I try to create an entry... will try to figure that out).

So, I'm sorry but I don't seem to be able to fix this for Windows 10...

**Comment by renatoathaydes** [comment]
BTW look what I found on my old Windows desktop:

![screenshot-windows](https://user-images.githubusercontent.com/1901277/34533416-6744425a-f0ba-11e7-8f76-49178d79c0ed.png)

I wasn't entirely wrong when I said Git Shell 💃
